### PR TITLE
New Vehicles

### PR DESCRIPTION
**Pull request by Dustybin320**
New vehicle adds requested:

Class 101, 107 (Strathclyde Orange)
Class 303 (Strathclyde Orange)
Class 320 (SPT, SPT Refurbished, ScotRail Saltire, Strathclyde Orange)
Class 318 (ScotRail Saltire)
Class 314 (ScotRail Saltire)
Class 322 (First ScotRail)
Class 156 (Strathclyde Orange, ScotRail Swoosh, SPT, First ScotRail, ScotRail Saltire)
Class 158 (ScotRail Swoosh, First ScotRail, ScotRail Saltire)
Class 185 (TPE Northern Star)
Class 350 (TPE Northern Star)
Class 390 (Avanti West Coast)
Class 43 HST (CrossCountry, ScotRail)

### CODE REVIEW

**Comment by jamespetts** [comment]
Hello again - I believe that this pull request is still aimed at a 
Standard branch (this time, my fork of the repository).

What would be easier for me to understand what this is relating to would 
be to give me the Github URL of the repository where you have pushed 
these new vehicles/liveries so that I can simply merge it using my 
desktop Git client.

Thank you for your work on this.

**Comment by Dustybin320** [comment]
https://github.com/jamespetts/simutrans-pak128.britain/pull/94
is the URL.

**Comment by jamespetts** [comment]
That is the pull request URL - do you have the repository URL so that I 
can add the repository to my desktop Git client?

**Comment by Rollmaterial** [comment]
There seems to be a misunderstanding of what a pull request is. A pull request is when you have committed some work to your own repository and would like it to be merged into the repository you are sending the request to. It is not meant as a feature request.

**Comment by jamespetts** [comment]
This does not appear to be a valid pull request, so closing this.

**Pull request closed without merging**
