### PR TITLE
 FIX: Mail is now able to be picked up by canal boats

### PR DESCRIPTION
**Pull request by Spenk009**
Added post to the different canal quays, since previously they were
unable to pick up post/mail.

### CODE REVIEW

**Comment by jamespetts** [comment]
Thank you for this. Is there a reason that you think that canal quays would have been able to process mail without the need for an associated post office (or is there a gameplay reason for not requiring the post office extension building for these)?

**Comment by Spenk009** [comment]
I spent a few hours at work thinking about it and have come to the conclusion to check the length of the convoy, to ensure the mail hold is within the stop. They have a length of 2 tiles and will pick up mail if the stop is two tiles long. This is due to no value being assigned to the length of the mail hold. 

This pull request can be denied, as neither a mailbox is on the stop (type) and the change isn't necessary to allow normal operation of vehicles. Is it possible to use vehicle "length=0" for the holds? Otherwise we can shorten the barge/narrwoboat and assign the hold a short length.

**Comment by Spenk009** [comment]
I've rescinded my statement asking to go through with the pull request. You're correct when it comes to quays being unable to process mail and they shouldn't. I hadn't seen the use of capacities that way and thought stops need to have the correct type of goods/mail/pax to allow transfer. Now I'm asking to edit the combination of vehicles to shorten it to a length that fits the convoy onto one station tile.

**Comment by jamespetts** [comment]
Thank you for clarifying. The trouble with changing the length of the 
vehicles is that the graphics will overlap, so I do not think that this 
is a viable option, I am afraid.

**Comment by Spenk009** [comment]
Then I presume that setting length=0 will hide the graphic entirely, which is not what we want. Maybe the simplest solution is to edit the vehicle comment to help guide users encountering the same issue. Should the help texts for boats be altered along the lines of: "This convoy requires two consecutive quay tiles to pick up mail."

**Comment by jamespetts** [comment]
May I ask what you mean when you refer to the "vehicle comment"?

**Comment by Spenk009** [comment]
I misread the "Author" tag as a comment/description tag. My apologies.

**Pull request closed without merging**
